services:
  apps:
    build: ./apps
    ports:
      - "10000:3000"
    restart: always
    env_file: ./apps/.env
    volumes:
      - /opt/jenkins/workspace/freestyle-job-simpleapps/simple-apps:/app
#volumes:
#  myapp:
#    external: true